// Class: Readgg_plus_trees100
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::gg_plus_trees100
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : dcurry
Date           : Sat Apr 22 15:04:40 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/d/dcurry/public/v25Heppy/CMSSW_7_4_7/src/VHbb/python
Training events: 138874
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "1.200000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "misclassificationerror" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
HCMVAV2_reg_mass              HCMVAV2_reg_mass              HCMVAV2_reg_mass              HCMVAV2_reg_mass                                                'D'    [90.0003662109,149.996246338]
HCMVAV2_reg_pt                HCMVAV2_reg_pt                HCMVAV2_reg_pt                HCMVAV2_reg_pt                                                  'D'    [0.735095620155,720.464172363]
VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi) VHbb_deltaPhi_HCMVAV2_reg_phi,V_new_phi_  VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi) VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi)                                               'D'    [-3.14159011841,3.14159154892]
hJetCMVA_btag_0               hJetCMVA_btag_0               hJetCMVA_btag_0               hJetCMVA_btag_0                                                 'D'    [-0.587541818619,0.999979674816]
hJetCMVA_btag_1               hJetCMVA_btag_1               hJetCMVA_btag_1               hJetCMVA_btag_1                                                 'D'    [-0.588310718536,0.999972224236]
hJetCMVA_pt_0                 hJetCMVA_pt_0                 hJetCMVA_pt_0                 hJetCMVA_pt_0                                                   'D'    [21.1099720001,551.63873291]
hJetCMVA_pt_1                 hJetCMVA_pt_1                 hJetCMVA_pt_1                 hJetCMVA_pt_1                                                   'D'    [18.3948364258,550.686828613]
V_new_mass                    V_new_mass                    V_new_mass                    V_new_mass                                                      'D'    [75.004524231,104.999214172]
Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1]))) Sum__Jet_pt_reg_30__abs_Jet_eta__2.4__Jet_puId__7__Jet_id_0__aJCidx___hJCMVAV2idx_0_____aJCidx___hJCMVAV2idx_1____ Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1]))) Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1])))                                                                                                                        'D'    [0,8]
V_new_pt                      V_new_pt                      V_new_pt                      V_new_pt                                                        'D'    [150.000778198,2595.61816406]
(HCMVAV2_reg_pt/V_new_pt)     _HCMVAV2_reg_pt_D_V_new_pt_   (HCMVAV2_reg_pt/V_new_pt)     (HCMVAV2_reg_pt/V_new_pt)                                       'D'    [0.00365713378415,4.42368364334]
abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])   abs_Jet_eta_hJCMVAV2idx_0___M_Jet_eta_hJCMVAV2idx_1___ abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])   abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])                                                              'D'    [1.78813934326e-07,3.33193445206]
softActivityVH_njets5         softActivityVH_njets5         softActivityVH_njets5         softActivityVH_njets5                                           'D'    [0,18]
VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi) VHbb_deltaR_HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi_  VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi) VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi)                                                                       'D'    [0.0200989451259,7.33905220032]
met_pt                        met_pt                        met_pt                        met_pt                                                          'D'    [0.0935168936849,1414.9654541]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new gg_plus_trees100Node
   
#ifndef gg_plus_trees100Node__def
#define gg_plus_trees100Node__def
   
class gg_plus_trees100Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   gg_plus_trees100Node ( gg_plus_trees100Node* left,gg_plus_trees100Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~gg_plus_trees100Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   gg_plus_trees100Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   gg_plus_trees100Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   gg_plus_trees100Node*   fLeft;     // pointer to the left daughter node
   gg_plus_trees100Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   gg_plus_trees100Node::~gg_plus_trees100Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool gg_plus_trees100Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool gg_plus_trees100Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Readgg_plus_trees100 : public IClassifierReader {

 public:

   // constructor
   Readgg_plus_trees100( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Readgg_plus_trees100" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HCMVAV2_reg_mass", "HCMVAV2_reg_pt", "VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi)", "hJetCMVA_btag_0", "hJetCMVA_btag_1", "hJetCMVA_pt_0", "hJetCMVA_pt_1", "V_new_mass", "Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1])))", "V_new_pt", "(HCMVAV2_reg_pt/V_new_pt)", "abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])", "softActivityVH_njets5", "VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi)", "met_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Readgg_plus_trees100() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<gg_plus_trees100Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Readgg_plus_trees100::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      gg_plus_trees100Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(gg_plus_trees100Node*)current->GetRight();
         else current=(gg_plus_trees100Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Readgg_plus_trees100::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.126496386469843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 98.5712, 0, 1, 0.717858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389011,-99) , 
11, 1.40676, 1, 0, 0.678185,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.195979,-99) , 
3, 0.848787, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.113738);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.731693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498212,-99) , 
0, 98.5712, 0, 0, 0.707165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365023,-99) , 
4, 0.697442, 0, 0, 0.43394,-99) , 
1, 103.554, 0, 0, 0.658343,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.217186,-99) , 
3, 0.848787, 0, 0, 0.496593,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.11118);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 101.428, 0, 1, 0.731211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458588,-99) , 
1, 103.554, 0, 0, 0.683845,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406232,-99) , 
6, 70.3435, 0, 0, 0.516362,-99) , 
NN(
0, 
0, 
0, 109.999, 0, -1, 0.203354,-99) , 
3, 0.924383, 0, 0, 0.309101,-99) , 
4, 0.168014, 0, 0, 0.495625,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.101531);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470071,-99) , 
1, 96.4621, 0, 0, 0.666833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364244,-99) , 
0, 138.568, 1, 0, 0.634459,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.251306,-99) , 
3, 0.848787, 0, 0, 0.495945,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0896245);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.70285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496678,-99) , 
0, 135.712, 1, 0, 0.677456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414603,-99) , 
11, 1.42411, 1, 0, 0.647302,-99) , 
NN(
0, 
0, 
0, 104.285, 0, -1, 0.307808,-99) , 
4, 0.0167495, 0, 0, 0.497027,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0884966);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459707,-99) , 
0, 96.9386, 0, 0, 0.641352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401637,-99) , 
0, 138.568, 1, 0, 0.615177,-99) , 
NN(
0, 
0, 
0, 109.999, 0, -1, 0.255355,-99) , 
3, 0.773191, 0, 0, 0.500179,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0842251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 101.428, 0, 1, 0.681662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481704,-99) , 
10, 0.424612, 0, 0, 0.654871,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437271,-99) , 
12, 1.52381, 1, 0, 0.509675,-99) , 
NN(
0, 
0, 
0, 109.999, 0, -1, 0.272412,-99) , 
3, 0.924383, 0, 0, 0.359632,-99) , 
4, 0.243647, 0, 0, 0.498435,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0774812);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482224,-99) , 
0, 98.5712, 0, 0, 0.622137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4043,-99) , 
11, 1.41818, 1, 0, 0.594453,-99) , 
NN(
0, 
0, 
0, 112.855, 0, -1, 0.260492,-99) , 
3, 0.697595, 0, 0, 0.499339,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0672476);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499665,-99) , 
0, 98.5712, 0, 0, 0.635709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447449,-99) , 
11, 1.42411, 1, 0, 0.613573,-99) , 
NN(
0, 
0, 
0, 104.285, 0, -1, 0.350035,-99) , 
4, 0.0167495, 0, 0, 0.497679,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.072261);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469262,-99) , 
1, 96.4621, 0, 0, 0.605358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396401,-99) , 
0, 138.568, 1, 0, 0.581879,-99) , 
NN(
0, 
0, 
0, 112.855, 0, -1, 0.261082,-99) , 
3, 0.621998, 0, 0, 0.500155,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0603887);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 98.7072, 0, 1, 0.66021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499896,-99) , 
0, 135.712, 1, 0, 0.637991,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53221,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.368511,-99) , 
8, 0.380952, 1, 0, 0.399443,-99) , 
4, 0.394912, 0, 0, 0.498395,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0630157);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48407,-99) , 
7, 95.0021, 1, 0, 0.619678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443761,-99) , 
13, 3.25448, 1, 0, 0.590136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556781,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.332403,-99) , 
4, 0.347329, 0, 0, 0.361222,-99) , 
3, 0.924383, 0, 0, 0.499401,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0650966);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470367,-99) , 
0, 104.285, 0, 0, 0.62299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428532,-99) , 
4, 0.773073, 0, 0, 0.467606,-99) , 
1, 137.826, 0, 0, 0.568016,-99) , 
NN(
0, 
0, 
0, 112.855, 0, -1, 0.294485,-99) , 
3, 0.621998, 0, 0, 0.499525,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0588142);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497692,-99) , 
8, 2.28571, 1, 0, 0.623634,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394499,-99) , 
4, 0.546196, 0, 0, 0.470227,-99) , 
10, 0.63509, 0, 0, 0.580774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445604,-99) , 
11, 0.725344, 1, 0, 0.502439,-99) , 
NN(
0, 
0, 
0, 112.855, 0, -1, 0.315411,-99) , 
3, 0.924383, 0, 0, 0.379216,-99) , 
4, -0.0588831, 0, 0, 0.500039,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.059645);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468802,-99) , 
13, 3.27422, 1, 0, 0.608664,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423316,-99) , 
11, 0.79117, 1, 0, 0.465474,-99) , 
1, 137.826, 0, 0, 0.557628,-99) , 
NN(
0, 
0, 
2, 0.149596, 1, -1, 0.278034,-99) , 
3, 0.470806, 0, 0, 0.499684,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0513185);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 100.884, 0, 1, 0.63441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487368,-99) , 
0, 135.712, 1, 0, 0.61335,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448732,-99) , 
6, 70.4725, 0, 0, 0.518559,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.37993,-99) , 
12, 1.71429, 1, 0, 0.431432,-99) , 
4, 0.546177, 0, 0, 0.498225,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0572276);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463437,-99) , 
5, 46.1734, 0, 0, 0.584717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416585,-99) , 
4, 0.697489, 0, 0, 0.456033,-99) , 
6, 45.4184, 0, 0, 0.552121,-99) , 
NN(
0, 
0, 
2, 0.149596, 1, -1, 0.295884,-99) , 
3, 0.470806, 0, 0, 0.499546,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0526658);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464476,-99) , 
0, 104.285, 0, 0, 0.592694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431292,-99) , 
0, 109.999, 1, 0, 0.468602,-99) , 
1, 137.826, 0, 0, 0.548131,-99) , 
NN(
0, 
0, 
2, 0.149596, 1, -1, 0.307975,-99) , 
3, 0.470806, 0, 0, 0.499104,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0486546);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471133,-99) , 
8, 2.28571, 1, 0, 0.600563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438836,-99) , 
9, 201.981, 0, 0, 0.465823,-99) , 
1, 137.826, 0, 0, 0.552303,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.381016,-99) , 
4, -0.210148, 0, 0, 0.498434,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0490141);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470593,-99) , 
12, 3.42857, 1, 0, 0.563477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396763,-99) , 
0, 138.568, 1, 0, 0.544175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311987,-99) , 
3, 0.39521, 0, 0, 0.50049,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0376798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 104.285, 0, 1, 0.641317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478557,-99) , 
1, 103.86, 0, 0, 0.608146,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534101,-99) , 
NN(
0, 
0, 
0, 98.5713, 0, -1, 0.432468,-99) , 
8, 0.380952, 1, 0, 0.452341,-99) , 
4, 0.697442, 0, 0, 0.499357,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0449613);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40685,-99) , 
14, 77.9339, 1, 0, 0.558885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410132,-99) , 
0, 138.568, 1, 0, 0.541692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327566,-99) , 
3, 0.39521, 0, 0, 0.501702,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0408935);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 107.142, 0, 1, 0.641754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484564,-99) , 
10, 0.636449, 0, 0, 0.596146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426023,-99) , 
0, 127.14, 1, 0, 0.516945,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.418295,-99) , 
12, 1.71429, 1, 0, 0.455646,-99) , 
4, 0.697442, 0, 0, 0.497935,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.040822);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460349,-99) , 
0, 104.285, 0, 0, 0.583044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449233,-99) , 
9, 201.981, 0, 0, 0.472167,-99) , 
1, 137.826, 0, 0, 0.543077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502295,-99) , 
NN(
0, 
0, 
1, 196.07, 0, -1, 0.357597,-99) , 
3, 0.924383, 0, 0, 0.405831,-99) , 
4, -0.210148, 0, 0, 0.500165,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0378224);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473722,-99) , 
8, 2.28571, 1, 0, 0.556986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416388,-99) , 
0, 138.568, 1, 0, 0.540822,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.408887,-99) , 
4, -0.210148, 0, 0, 0.499591,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.040298);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465868,-99) , 
5, 46.1734, 0, 0, 0.558665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439788,-99) , 
4, 0.773107, 0, 0, 0.461555,-99) , 
6, 45.4184, 0, 0, 0.533889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353201,-99) , 
3, 0.39521, 0, 0, 0.500576,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0369964);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468702,-99) , 
0, 104.285, 0, 0, 0.552832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412282,-99) , 
0, 118.571, 1, 0, 0.465826,-99) , 
6, 45.4184, 0, 0, 0.530577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346015,-99) , 
3, 0.319613, 0, 0, 0.500235,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0363888);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 109.999, 0, 1, 0.631199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466845,-99) , 
5, 64.5867, 0, 0, 0.488119,-99) , 
1, 138.116, 0, 0, 0.577825,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444272,-99) , 
11, 0.945541, 1, 0, 0.513487,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.417107,-99) , 
8, 1.14286, 1, 0, 0.46427,-99) , 
4, 0.697442, 0, 0, 0.49835,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0371142);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43699,-99) , 
13, 3.30359, 1, 0, 0.565688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447308,-99) , 
4, 0.805485, 0, 0, 0.475765,-99) , 
5, 71.6365, 0, 0, 0.528674,-99) , 
NN(
0, 
0, 
0, 115.713, 0, -1, 0.389775,-99) , 
4, -0.361413, 0, 0, 0.499081,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0333146);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480689,-99) , 
0, 104.285, 0, 0, 0.573097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434355,-99) , 
0, 132.855, 1, 0, 0.545268,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490189,-99) , 
0, 115.715, 0, 0, 0.531677,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.437169,-99) , 
4, 0.92433, 0, 0, 0.455897,-99) , 
8, 1.14286, 1, 0, 0.498969,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.034398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437572,-99) , 
0, 138.569, 1, 0, 0.541912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42168,-99) , 
7, 95.001, 1, 0, 0.528264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365565,-99) , 
3, 0.319613, 0, 0, 0.501811,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.035389);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443065,-99) , 
5, 46.3732, 0, 0, 0.559638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398824,-99) , 
13, 3.27039, 1, 0, 0.532282,-99) , 
NN(
0, 
0, 
0, 101.429, 1, -1, 0.442214,-99) , 
1, 137.826, 0, 0, 0.499131,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0316703);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449031,-99) , 
0, 138.568, 1, 0, 0.544519,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403311,-99) , 
14, 39.7873, 1, 0, 0.464827,-99) , 
6, 45.4184, 0, 0, 0.524008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358071,-99) , 
3, 0.244017, 0, 0, 0.500245,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0305781);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452898,-99) , 
13, 2.77618, 0, 0, 0.565519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449894,-99) , 
13, 3.23068, 1, 0, 0.538935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488488,-99) , 
0, 115.715, 0, 0, 0.522864,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.442438,-99) , 
4, 0.92433, 0, 0, 0.458395,-99) , 
8, 1.14286, 1, 0, 0.497164,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0291508);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470894,-99) , 
5, 47.3194, 0, 0, 0.54406,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45513,-99) , 
4, 0.935135, 0, 0, 0.467946,-99) , 
8, 2.28571, 1, 0, 0.524116,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345961,-99) , 
3, 0.773191, 0, 0, 0.406958,-99) , 
4, -0.361413, 0, 0, 0.499346,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0330833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436079,-99) , 
0, 135.712, 1, 0, 0.539549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396719,-99) , 
1, 173.542, 0, 0, 0.464677,-99) , 
14, 51.9871, 1, 0, 0.521991,-99) , 
NN(
0, 
0, 
0, 115.713, 0, -1, 0.408374,-99) , 
4, -0.361413, 0, 0, 0.497995,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0280822);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475718,-99) , 
6, 45.6179, 0, 0, 0.561742,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414157,-99) , 
11, 0.787892, 1, 0, 0.461121,-99) , 
1, 138.116, 0, 0, 0.532522,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474983,-99) , 
10, 0.742766, 0, 0, 0.512609,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440397,-99) , 
12, 1.71429, 1, 0, 0.450424,-99) , 
4, 0.92433, 0, 0, 0.46279,-99) , 
8, 1.14286, 1, 0, 0.496325,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0254139);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492312,-99) , 
10, 0.63655, 0, 0, 0.570873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456225,-99) , 
3, 0.985821, 0, 0, 0.5501,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451472,-99) , 
2, 3.04186, 0, 0, 0.510517,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448521,-99) , 
11, 0.317343, 1, 0, 0.458967,-99) , 
2, 2.84239, 0, 0, 0.474344,-99) , 
4, 0.697442, 0, 0, 0.49707,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.028256);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470972,-99) , 
0, 104.285, 0, 0, 0.536428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445635,-99) , 
0, 107.145, 1, 0, 0.465896,-99) , 
6, 45.4308, 0, 0, 0.518143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35947,-99) , 
3, 0.168421, 0, 0, 0.498581,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0312461);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450204,-99) , 
0, 104.285, 0, 0, 0.562115,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42128,-99) , 
6, 36.4733, 0, 0, 0.451205,-99) , 
6, 43.7059, 0, 0, 0.524445,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51597,-99) , 
NN(
0, 
0, 
0, 104.285, 1, -1, 0.441905,-99) , 
4, 0.848704, 0, 0, 0.459205,-99) , 
5, 71.6365, 0, 0, 0.497513,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0244199);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460072,-99) , 
13, 2.77618, 0, 0, 0.554522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449075,-99) , 
13, 3.23068, 1, 0, 0.530168,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48625,-99) , 
2, 3.01336, 0, 0, 0.508557,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.457581,-99) , 
2, 2.84239, 0, 0, 0.468436,-99) , 
8, 1.14286, 1, 0, 0.498096,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0319121);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397728,-99) , 
14, 77.9339, 1, 0, 0.536344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373826,-99) , 
13, 3.36144, 1, 0, 0.469004,-99) , 
13, 3.16254, 1, 0, 0.517878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370147,-99) , 
3, 0.168421, 0, 0, 0.499779,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0262457);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495074,-99) , 
2, 2.97062, 0, 0, 0.568652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475606,-99) , 
13, 3.21282, 1, 0, 0.54239,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46205,-99) , 
13, 3.18312, 1, 0, 0.522332,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.444213,-99) , 
2, -2.85664, 1, 0, 0.477259,-99) , 
2, 2.84239, 0, 0, 0.496089,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0271154);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410782,-99) , 
10, 1.16477, 1, 0, 0.528795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445818,-99) , 
0, 135.712, 1, 0, 0.516286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39975,-99) , 
4, -0.437046, 0, 0, 0.498156,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0276795);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452286,-99) , 
0, 104.285, 0, 0, 0.554425,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42774,-99) , 
6, 36.4733, 0, 0, 0.453464,-99) , 
6, 43.7059, 0, 0, 0.520106,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51568,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.453886,-99) , 
12, 0.809524, 1, 0, 0.462268,-99) , 
5, 71.6365, 0, 0, 0.496207,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0293247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468173,-99) , 
5, 46.1177, 0, 0, 0.541898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389977,-99) , 
13, 3.31768, 1, 0, 0.521475,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462142,-99) , 
10, 0.703661, 0, 0, 0.509436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437593,-99) , 
4, 0.848707, 0, 0, 0.450803,-99) , 
6, 52.191, 0, 0, 0.466678,-99) , 
6, 69.0893, 0, 0, 0.497287,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0235171);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454012,-99) , 
0, 138.569, 1, 0, 0.52461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426036,-99) , 
7, 95.001, 1, 0, 0.513598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38497,-99) , 
3, 0.168421, 0, 0, 0.497995,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0232999);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 109.999, 0, 1, 0.558539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476712,-99) , 
2, 2.97062, 0, 0, 0.538537,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451492,-99) , 
0, 107.144, 0, 0, 0.516699,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.450385,-99) , 
2, -2.85664, 1, 0, 0.478406,-99) , 
2, 2.84239, 0, 0, 0.495772,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0232087);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486702,-99) , 
8, 2.28571, 1, 0, 0.553706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451454,-99) , 
3, 0.985821, 0, 0, 0.535054,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418969,-99) , 
5, 45.7001, 0, 0, 0.508099,-99) , 
NN(
0, 
0, 
0, 101.429, 1, -1, 0.468598,-99) , 
6, 119.784, 0, 0, 0.480112,-99) , 
4, 0.697442, 0, 0, 0.496583,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0221451);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440712,-99) , 
7, 85.4787, 0, 0, 0.523685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437525,-99) , 
7, 95.001, 1, 0, 0.514239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41534,-99) , 
4, -0.437046, 0, 0, 0.498959,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0214118);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 109.999, 0, 1, 0.558405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476725,-99) , 
13, 3.21282, 1, 0, 0.535295,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474725,-99) , 
2, -3.07375, 1, 0, 0.514208,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.45755,-99) , 
2, -2.85664, 1, 0, 0.48149,-99) , 
2, 2.84239, 0, 0, 0.497032,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0251426);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456793,-99) , 
7, 95.0021, 1, 0, 0.529682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426996,-99) , 
3, 0.245251, 0, 0, 0.515758,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492572,-99) , 
6, 98.4014, 0, 0, 0.52896,-99) , 
NN(
0, 
0, 
0, 115.712, 0, -1, 0.398692,-99) , 
12, 1.71429, 1, 0, 0.456457,-99) , 
13, 3.15679, 1, 0, 0.498819,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0238565);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477021,-99) , 
0, 104.285, 0, 0, 0.539299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4441,-99) , 
0, 132.855, 1, 0, 0.52024,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426572,-99) , 
3, 0.47167, 0, 0, 0.501273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39277,-99) , 
13, 3.15679, 1, 0, 0.476506,-99) , 
8, 1.14286, 1, 0, 0.497492,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0174832);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483011,-99) , 
0, 104.285, 0, 0, 0.536767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45004,-99) , 
0, 132.855, 1, 0, 0.519404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504203,-99) , 
NN(
0, 
0, 
0, 98.5713, 0, -1, 0.469198,-99) , 
12, 1.71429, 1, 0, 0.474936,-99) , 
8, 1.14286, 1, 0, 0.496273,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0219836);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460352,-99) , 
0, 104.285, 0, 0, 0.542499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443008,-99) , 
6, 36.4733, 0, 0, 0.464823,-99) , 
6, 43.7059, 0, 0, 0.516033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448572,-99) , 
7, 89.2869, 1, 0, 0.462925,-99) , 
4, 0.924336, 0, 0, 0.471226,-99) , 
5, 71.6365, 0, 0, 0.4975,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0211478);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480933,-99) , 
2, 2.98487, 0, 0, 0.554318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477332,-99) , 
11, 1.0191, 1, 0, 0.531869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468151,-99) , 
2, -3.03304, 1, 0, 0.513862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444573,-99) , 
9, 237.763, 0, 0, 0.460559,-99) , 
2, -2.85664, 1, 0, 0.483078,-99) , 
2, 2.84239, 0, 0, 0.497165,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0191905);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486217,-99) , 
2, 2.98487, 0, 0, 0.552084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482645,-99) , 
11, 1.0191, 1, 0, 0.531822,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466581,-99) , 
13, 3.18312, 1, 0, 0.512874,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.462905,-99) , 
2, -2.85664, 1, 0, 0.484016,-99) , 
2, 2.84239, 0, 0, 0.497816,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0231057);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449871,-99) , 
0, 135.712, 1, 0, 0.524816,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43595,-99) , 
12, 1.52381, 1, 0, 0.470509,-99) , 
14, 51.9871, 1, 0, 0.512324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427797,-99) , 
4, -0.437046, 0, 0, 0.499347,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0228508);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481886,-99) , 
14, 51.9871, 1, 0, 0.523563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440777,-99) , 
3, 0.245251, 0, 0, 0.512386,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480053,-99) , 
12, 1.71429, 1, 0, 0.522123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37422,-99) , 
13, 3.35595, 1, 0, 0.461807,-99) , 
13, 3.15679, 1, 0, 0.497976,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0182344);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492168,-99) , 
0, 115.712, 0, 0, 0.547653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485573,-99) , 
11, 1.0191, 1, 0, 0.529532,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476471,-99) , 
2, -3.07375, 1, 0, 0.509512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452483,-99) , 
9, 237.763, 0, 0, 0.465891,-99) , 
2, -2.85664, 1, 0, 0.484328,-99) , 
2, 2.84239, 0, 0, 0.497381,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0193717);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462363,-99) , 
0, 135.712, 1, 0, 0.517779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407872,-99) , 
10, 1.26652, 1, 0, 0.510096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400629,-99) , 
3, 0.0928245, 0, 0, 0.498849,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0165302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 109.999, 0, 1, 0.543227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484332,-99) , 
2, 2.97062, 0, 0, 0.528731,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461676,-99) , 
3, 0.924708, 0, 0, 0.510584,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.470265,-99) , 
14, 26.0403, 1, 0, 0.483873,-99) , 
2, 2.84239, 0, 0, 0.496823,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0221178);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441751,-99) , 
7, 84.731, 0, 0, 0.522367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429964,-99) , 
1, 169.502, 0, 0, 0.464228,-99) , 
7, 93.5728, 1, 0, 0.511941,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48582,-99) , 
13, 3.21369, 1, 0, 0.520174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379394,-99) , 
13, 3.35595, 1, 0, 0.46285,-99) , 
13, 3.15679, 1, 0, 0.497967,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0208007);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46584,-99) , 
0, 115.711, 0, 0, 0.555077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46276,-99) , 
4, 0.621824, 0, 0, 0.480291,-99) , 
6, 69.0169, 0, 0, 0.512567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501258,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.463815,-99) , 
2, 2.84239, 0, 0, 0.47322,-99) , 
5, 71.6365, 0, 0, 0.496283,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.018532);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475281,-99) , 
0, 109.998, 0, 0, 0.535672,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451458,-99) , 
6, 36.4733, 0, 0, 0.470388,-99) , 
6, 43.7059, 0, 0, 0.513377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500219,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458048,-99) , 
7, 89.2869, 1, 0, 0.47005,-99) , 
4, 0.924336, 0, 0, 0.475803,-99) , 
5, 71.6365, 0, 0, 0.497821,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0183806);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489944,-99) , 
1, 156.185, 0, 0, 0.53027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458276,-99) , 
0, 132.855, 1, 0, 0.515863,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479733,-99) , 
9, 233.574, 0, 0, 0.505355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446101,-99) , 
13, 3.02403, 1, 0, 0.46572,-99) , 
13, 2.80827, 1, 0, 0.481373,-99) , 
8, 1.14286, 1, 0, 0.497896,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0175199);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459011,-99) , 
0, 138.568, 1, 0, 0.51648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41076,-99) , 
10, 1.26652, 1, 0, 0.5091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410223,-99) , 
3, 0.0928245, 0, 0, 0.498987,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0185193);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468829,-99) , 
0, 115.711, 0, 0, 0.550102,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451857,-99) , 
0, 118.573, 1, 0, 0.482504,-99) , 
6, 69.0169, 0, 0, 0.511641,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.476034,-99) , 
5, 71.6365, 0, 0, 0.496894,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0188758);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465012,-99) , 
7, 95.0021, 1, 0, 0.518833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458388,-99) , 
3, 0.245251, 0, 0, 0.510695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488274,-99) , 
12, 1.71429, 1, 0, 0.522303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388222,-99) , 
13, 3.35595, 1, 0, 0.46787,-99) , 
13, 3.15679, 1, 0, 0.498522,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0164894);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480103,-99) , 
11, 0.307427, 0, 0, 0.526612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465118,-99) , 
0, 132.855, 1, 0, 0.514315,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476404,-99) , 
6, 69.0893, 0, 0, 0.504473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44582,-99) , 
0, 121.426, 0, 0, 0.466707,-99) , 
13, 2.80827, 1, 0, 0.481625,-99) , 
8, 1.14286, 1, 0, 0.497285,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0164564);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490529,-99) , 
0, 115.712, 0, 0, 0.539333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483013,-99) , 
11, 1.0191, 1, 0, 0.522829,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453013,-99) , 
2, -2.97877, 1, 0, 0.510824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406174,-99) , 
13, 2.80827, 1, 0, 0.469404,-99) , 
2, -2.85664, 1, 0, 0.486907,-99) , 
2, 2.84239, 0, 0, 0.49728,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0154736);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498883,-99) , 
12, 2.66667, 1, 0, 0.537289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484051,-99) , 
2, 2.97062, 0, 0, 0.524134,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460575,-99) , 
0, 107.144, 0, 0, 0.50871,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.46797,-99) , 
2, -2.85664, 1, 0, 0.485185,-99) , 
2, 2.84239, 0, 0, 0.496432,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0148985);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486597,-99) , 
2, 2.98487, 0, 0, 0.539189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486825,-99) , 
11, 1.0191, 1, 0, 0.523832,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469927,-99) , 
3, 0.924708, 0, 0, 0.509868,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469252,-99) , 
0, 101.428, 1, 0, 0.474955,-99) , 
14, 26.0403, 1, 0, 0.48675,-99) , 
2, 2.84239, 0, 0, 0.497458,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0180404);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451153,-99) , 
7, 85.0049, 0, 0, 0.517519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464824,-99) , 
4, -0.437025, 0, 0, 0.509821,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481856,-99) , 
1, 208.443, 1, 0, 0.521057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394184,-99) , 
13, 3.35595, 1, 0, 0.469662,-99) , 
13, 3.15679, 1, 0, 0.498422,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0150594);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492085,-99) , 
0, 115.712, 0, 0, 0.536778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489027,-99) , 
11, 1.0191, 1, 0, 0.522764,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479632,-99) , 
2, -3.07375, 1, 0, 0.507488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458868,-99) , 
10, 0.424612, 1, 0, 0.471115,-99) , 
2, -2.85664, 1, 0, 0.486488,-99) , 
2, 2.84239, 0, 0, 0.496963,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0137856);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 112.861, 0, 1, 0.541211,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486695,-99) , 
8, 1.14286, 0, 0, 0.493879,-99) , 
2, 3.01336, 0, 0, 0.523959,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463146,-99) , 
0, 107.144, 0, 0, 0.508095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41582,-99) , 
13, 2.80827, 1, 0, 0.472635,-99) , 
2, -2.85664, 1, 0, 0.487622,-99) , 
2, 2.84239, 0, 0, 0.498114,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0166983);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592049,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4581,-99) , 
2, 3.04186, 0, 0, 0.495163,-99) , 
4, 0.697453, 0, 0, 0.521788,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472837,-99) , 
1, 161.272, 0, 0, 0.506702,-99) , 
NN(
0, 
0, 
0, 101.428, 0, -1, 0.471429,-99) , 
2, -2.85664, 1, 0, 0.486337,-99) , 
2, 2.84239, 0, 0, 0.496573,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0184833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451415,-99) , 
7, 84.731, 0, 0, 0.517199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424705,-99) , 
7, 95.7493, 1, 0, 0.470527,-99) , 
7, 93.5728, 1, 0, 0.508847,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480805,-99) , 
1, 208.443, 1, 0, 0.517405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398516,-99) , 
13, 3.35595, 1, 0, 0.469315,-99) , 
13, 3.15679, 1, 0, 0.49764,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0152705);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460225,-99) , 
2, 3.04186, 0, 0, 0.493439,-99) , 
4, 0.697453, 0, 0, 0.518996,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463278,-99) , 
14, 12.449, 0, 0, 0.50676,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.475983,-99) , 
14, 26.0403, 1, 0, 0.486387,-99) , 
2, 2.84239, 0, 0, 0.495802,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0253117);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467638,-99) , 
1, 179.26, 0, 0, 0.537814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357414,-99) , 
10, 0.956397, 1, 0, 0.475353,-99) , 
0, 115.713, 0, 0, 0.509822,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484826,-99) , 
2, 1.34632, 0, 0, 0.51492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458252,-99) , 
0, 101.429, 1, 0, 0.468007,-99) , 
6, 52.191, 0, 0, 0.480666,-99) , 
6, 69.0893, 0, 0, 0.49691,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0156451);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451399,-99) , 
13, 3.29036, 1, 0, 0.521665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407327,-99) , 
5, 231.638, 1, 0, 0.509774,-99) , 
NN(
0, 
0, 
0, 101.428, 1, -1, 0.479941,-99) , 
5, 71.6365, 0, 0, 0.497401,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0227943);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467435,-99) , 
0, 129.998, 1, 0, 0.516173,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33029,-99) , 
0, 121.417, 0, 0, 0.453987,-99) , 
1, 274.918, 1, 0, 0.506588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448936,-99) , 
4, -0.437046, 0, 0, 0.497798,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0157684);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472219,-99) , 
13, 3.23458, 1, 0, 0.523258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474291,-99) , 
11, 1.10304, 1, 0, 0.510338,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482683,-99) , 
9, 233.574, 0, 0, 0.504294,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452673,-99) , 
13, 3.02403, 1, 0, 0.470244,-99) , 
13, 2.80827, 1, 0, 0.483731,-99) , 
8, 1.14286, 1, 0, 0.496463,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0150215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579642,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466845,-99) , 
7, 90.7316, 1, 0, 0.493041,-99) , 
4, 0.697453, 0, 0, 0.516808,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48163,-99) , 
2, -3.07375, 1, 0, 0.506715,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464982,-99) , 
10, 0.424612, 1, 0, 0.475931,-99) , 
2, -2.85664, 1, 0, 0.488937,-99) , 
2, 2.84239, 0, 0, 0.496977,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0228634);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459183,-99) , 
0, 136.936, 1, 0, 0.538497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363459,-99) , 
10, 0.956397, 1, 0, 0.473,-99) , 
0, 115.713, 0, 0, 0.509141,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484667,-99) , 
10, 0.703661, 0, 0, 0.515393,-99) , 
NN(
0, 
0, 
0, 101.429, 1, -1, 0.47107,-99) , 
6, 52.191, 0, 0, 0.48302,-99) , 
6, 69.0893, 0, 0, 0.497568,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.024512);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473173,-99) , 
11, 1.12949, 1, 0, 0.537674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469334,-99) , 
0, 101.429, 1, 0, 0.483473,-99) , 
1, 157.41, 0, 0, 0.506661,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339514,-99) , 
0, 121.425, 0, 0, 0.451009,-99) , 
1, 274.918, 1, 0, 0.498147,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0217785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478855,-99) , 
0, 132.855, 1, 0, 0.53391,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475452,-99) , 
0, 101.429, 1, 0, 0.486995,-99) , 
1, 157.41, 0, 0, 0.507061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345073,-99) , 
0, 121.425, 0, 0, 0.451159,-99) , 
1, 274.918, 1, 0, 0.498524,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0203853);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453551,-99) , 
6, 31.9412, 0, 0, 0.516328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458321,-99) , 
0, 135.712, 1, 0, 0.507531,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32666,-99) , 
0, 118.568, 0, 0, 0.451292,-99) , 
1, 274.918, 1, 0, 0.498955,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0241354);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481103,-99) , 
1, 161.33, 0, 0, 0.520584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436214,-99) , 
0, 141.154, 1, 0, 0.508231,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487574,-99) , 
10, 0.619692, 0, 0, 0.523909,-99) , 
NN(
0, 
0, 
1, 230.39, 1, -1, 0.369236,-99) , 
10, 0.927568, 1, 0, 0.480388,-99) , 
0, 112.856, 0, 0, 0.496837,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0186066);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435539,-99) , 
14, 69.939, 1, 0, 0.5144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462494,-99) , 
4, -0.437025, 0, 0, 0.506468,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352759,-99) , 
0, 121.425, 0, 0, 0.448736,-99) , 
1, 274.918, 1, 0, 0.49768,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0210109);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469029,-99) , 
3, 0.245251, 0, 0, 0.524995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46703,-99) , 
9, 266.461, 0, 0, 0.487449,-99) , 
4, 0.168027, 1, 0, 0.505255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549207,-99) , 
NN(
0, 
0, 
0, 109.998, 0, -1, 0.452354,-99) , 
12, 0.857143, 1, 0, 0.470922,-99) , 
13, 3.15679, 1, 0, 0.495544,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0214039);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445895,-99) , 
10, 1.04374, 1, 0, 0.516681,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453945,-99) , 
1, 183.563, 0, 0, 0.48339,-99) , 
0, 124.284, 1, 0, 0.505587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357125,-99) , 
0, 121.425, 0, 0, 0.448804,-99) , 
1, 274.918, 1, 0, 0.496957,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0231068);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462429,-99) , 
5, 46.3156, 0, 0, 0.553892,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470412,-99) , 
14, 23.4253, 1, 0, 0.486318,-99) , 
6, 122.298, 0, 0, 0.507774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474757,-99) , 
0, 109.59, 1, 0, 0.515989,-99) , 
NN(
0, 
0, 
0, 105.918, 0, -1, 0.395898,-99) , 
10, 0.927568, 1, 0, 0.481239,-99) , 
0, 115.713, 0, 0, 0.495226,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0217641);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471869,-99) , 
8, 2.28571, 1, 0, 0.519506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44295,-99) , 
0, 141.154, 1, 0, 0.508301,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484741,-99) , 
10, 0.707656, 0, 0, 0.514507,-99) , 
NN(
0, 
0, 
1, 230.39, 1, -1, 0.382686,-99) , 
10, 0.927568, 1, 0, 0.477596,-99) , 
0, 112.856, 0, 0, 0.49575,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0192259);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486701,-99) , 
1, 161.33, 0, 0, 0.516918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448331,-99) , 
0, 141.154, 1, 0, 0.506884,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49018,-99) , 
10, 0.707656, 0, 0, 0.515531,-99) , 
NN(
0, 
0, 
1, 230.39, 1, -1, 0.387852,-99) , 
10, 0.927568, 1, 0, 0.479827,-99) , 
0, 112.856, 0, 0, 0.495827,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0201667);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471169,-99) , 
7, 86.4311, 0, 0, 0.518235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462262,-99) , 
4, 0.773069, 0, 0, 0.481611,-99) , 
0, 124.284, 1, 0, 0.506162,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49545,-99) , 
8, 1.14286, 1, 0, 0.544484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368502,-99) , 
0, 118.568, 0, 0, 0.462468,-99) , 
1, 240.645, 1, 0, 0.496849,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0189623);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479552,-99) , 
0, 132.038, 1, 0, 0.522303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471556,-99) , 
6, 46.7, 0, 0, 0.508447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478078,-99) , 
0, 109.59, 1, 0, 0.511844,-99) , 
NN(
0, 
0, 
0, 105.918, 0, -1, 0.408945,-99) , 
10, 0.927568, 1, 0, 0.482194,-99) , 
0, 115.713, 0, 0, 0.496038,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0166256);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481881,-99) , 
0, 139.385, 1, 0, 0.517141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460961,-99) , 
4, -0.437046, 0, 0, 0.508486,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488002,-99) , 
2, 2.24398, 0, 0, 0.51016,-99) , 
NN(
0, 
0, 
1, 230.39, 1, -1, 0.397165,-99) , 
10, 0.927568, 1, 0, 0.478652,-99) , 
0, 112.856, 0, 0, 0.496301,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0160668);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481004,-99) , 
5, 47.3732, 0, 0, 0.514711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444865,-99) , 
7, 95.0007, 1, 0, 0.50689,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488656,-99) , 
5, 71.6365, 0, 0, 0.511248,-99) , 
NN(
0, 
0, 
1, 230.39, 1, -1, 0.40116,-99) , 
10, 0.927568, 1, 0, 0.480579,-99) , 
0, 112.856, 0, 0, 0.496146,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0203085);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475568,-99) , 
3, 0.245251, 0, 0, 0.523081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470133,-99) , 
9, 266.461, 0, 0, 0.488907,-99) , 
4, 0.168027, 1, 0, 0.505127,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477318,-99) , 
1, 208.443, 1, 0, 0.512914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411117,-99) , 
13, 3.35595, 1, 0, 0.471649,-99) , 
13, 3.15679, 1, 0, 0.495676,-99)    );
   return;
};
 
// Clean up
inline void Readgg_plus_trees100::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Readgg_plus_trees100::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
