// Class: Readgg_plus_depth1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::gg_plus_depth1
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : dcurry
Date           : Sat Apr 22 07:38:02 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/d/dcurry/public/v25Heppy/CMSSW_7_4_7/src/VHbb/python
Training events: 191481
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "400" [Number of trees in the forest]
MaxDepth: "1" [Max depth of the decision tree allowed]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "1.200000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "misclassificationerror" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
HCMVAV2_reg_mass              HCMVAV2_reg_mass              HCMVAV2_reg_mass              HCMVAV2_reg_mass                                                'D'    [90.0001983643,149.998275757]
HCMVAV2_reg_pt                HCMVAV2_reg_pt                HCMVAV2_reg_pt                HCMVAV2_reg_pt                                                  'D'    [0.613469600677,716.475769043]
VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi) VHbb_deltaPhi_HCMVAV2_reg_phi,V_new_phi_  VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi) VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi)                                               'D'    [-3.14159226418,3.14159226418]
hJetCMVA_btag_0               hJetCMVA_btag_0               hJetCMVA_btag_0               hJetCMVA_btag_0                                                 'D'    [-0.586212575436,0.999980866909]
hJetCMVA_btag_1               hJetCMVA_btag_1               hJetCMVA_btag_1               hJetCMVA_btag_1                                                 'D'    [-0.588347494602,0.9999756217]
hJetCMVA_pt_0                 hJetCMVA_pt_0                 hJetCMVA_pt_0                 hJetCMVA_pt_0                                                   'D'    [18.5883846283,552.50793457]
hJetCMVA_pt_1                 hJetCMVA_pt_1                 hJetCMVA_pt_1                 hJetCMVA_pt_1                                                   'D'    [20.5966968536,550.094787598]
V_new_mass                    V_new_mass                    V_new_mass                    V_new_mass                                                      'D'    [75.0005187988,104.999343872]
Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1]))) Sum__Jet_pt_reg_30__abs_Jet_eta__2.4__Jet_puId__7__Jet_id_0__aJCidx___hJCMVAV2idx_0_____aJCidx___hJCMVAV2idx_1____ Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1]))) Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1])))                                                                                                                        'D'    [0,8]
V_new_pt                      V_new_pt                      V_new_pt                      V_new_pt                                                        'D'    [50.0001335144,149.999511719]
(HCMVAV2_reg_pt/V_new_pt)     _HCMVAV2_reg_pt_D_V_new_pt_   (HCMVAV2_reg_pt/V_new_pt)     (HCMVAV2_reg_pt/V_new_pt)                                       'D'    [0.00779384141788,11.6277208328]
abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])   abs_Jet_eta_hJCMVAV2idx_0___M_Jet_eta_hJCMVAV2idx_1___ abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])   abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])                                                              'D'    [2.26497650146e-06,3.30484580994]
softActivityVH_njets5         softActivityVH_njets5         softActivityVH_njets5         softActivityVH_njets5                                           'D'    [0,18]
VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi) VHbb_deltaR_HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi_  VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi) VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi)                                                                       'D'    [0.0156677495688,7.91000175476]
met_pt                        met_pt                        met_pt                        met_pt                                                          'D'    [0.0835502073169,729.457275391]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new gg_plus_depth1Node
   
#ifndef gg_plus_depth1Node__def
#define gg_plus_depth1Node__def
   
class gg_plus_depth1Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   gg_plus_depth1Node ( gg_plus_depth1Node* left,gg_plus_depth1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~gg_plus_depth1Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   gg_plus_depth1Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   gg_plus_depth1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   gg_plus_depth1Node*   fLeft;     // pointer to the left daughter node
   gg_plus_depth1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   gg_plus_depth1Node::~gg_plus_depth1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool gg_plus_depth1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool gg_plus_depth1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Readgg_plus_depth1 : public IClassifierReader {

 public:

   // constructor
   Readgg_plus_depth1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Readgg_plus_depth1" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HCMVAV2_reg_mass", "HCMVAV2_reg_pt", "VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi)", "hJetCMVA_btag_0", "hJetCMVA_btag_1", "hJetCMVA_pt_0", "hJetCMVA_pt_1", "V_new_mass", "Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1])))", "V_new_pt", "(HCMVAV2_reg_pt/V_new_pt)", "abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])", "softActivityVH_njets5", "VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi)", "met_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Readgg_plus_depth1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<gg_plus_depth1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Readgg_plus_depth1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      gg_plus_depth1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(gg_plus_depth1Node*)current->GetRight();
         else current=(gg_plus_depth1Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Readgg_plus_depth1::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.0767523618520538);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273297,-99) , 
3, 0.924448, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.0712826);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325686,-99) , 
4, 0.0923624, 0, 0, 0.493948,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.0635613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295816,-99) , 
3, 0.924448, 0, 0, 0.491568,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0592332);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351943,-99) , 
4, 0.167997, 0, 0, 0.486375,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0536403);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35511,-99) , 
11, 1.10162, 1, 0, 0.485046,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0526274);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281661,-99) , 
3, 0.848915, 0, 0, 0.483197,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0524006);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399406,-99) , 
9, 97.6189, 0, 0, 0.477474,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0495378);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347965,-99) , 
4, 0.016728, 0, 0, 0.481399,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0468202);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402098,-99) , 
9, 92.857, 0, 0, 0.478784,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0463159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341443,-99) , 
11, 1.25899, 1, 0, 0.481195,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.043975);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401878,-99) , 
4, 0.546169, 0, 0, 0.477909,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0420514);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308812,-99) , 
3, 0.848915, 0, 0, 0.479558,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0426904);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418462,-99) , 
9, 102.381, 0, 0, 0.474873,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0407373);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395108,-99) , 
11, 0.944243, 1, 0, 0.479069,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0381266);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297842,-99) , 
3, 0.773382, 0, 0, 0.479077,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0383351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424415,-99) , 
9, 102.381, 0, 0, 0.474187,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0368128);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387342,-99) , 
14, 34.8156, 1, 0, 0.477961,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0362014);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415305,-99) , 
11, 0.78687, 1, 0, 0.47676,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0355027);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378279,-99) , 
4, 0.016728, 0, 0, 0.478202,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0347083);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41316,-99) , 
9, 88.0951, 0, 0, 0.476241,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0330512);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37175,-99) , 
11, 1.25899, 1, 0, 0.477124,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0331632);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392379,-99) , 
14, 34.8156, 1, 0, 0.474713,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.03299);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43901,-99) , 
9, 111.905, 0, 0, 0.473639,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0333341);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291035,-99) , 
3, 0.697849, 0, 0, 0.478233,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0324237);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438134,-99) , 
2, 2.84239, 0, 0, 0.473468,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0308366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367113,-99) , 
3, 0.924448, 0, 0, 0.477648,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0306951);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441262,-99) , 
2, -2.84239, 1, 0, 0.474909,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0299622);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355365,-99) , 
11, 1.41636, 1, 0, 0.478839,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0300467);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442763,-99) , 
2, 2.84239, 0, 0, 0.47563,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0297717);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405675,-99) , 
14, 34.8156, 1, 0, 0.479503,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0295573);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36942,-99) , 
4, -0.134541, 0, 0, 0.478535,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0292449);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445373,-99) , 
9, 111.905, 0, 0, 0.475798,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0280802);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316533,-99) , 
3, 0.697849, 0, 0, 0.479868,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0284776);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444866,-99) , 
2, -2.84239, 1, 0, 0.475813,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0272666);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433227,-99) , 
11, 0.78687, 1, 0, 0.479453,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0268904);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450235,-99) , 
2, 2.84239, 0, 0, 0.480511,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0272405);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.160699,-99) , 
14, 69.5477, 1, 0, 0.483972,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0266566);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422645,-99) , 
9, 83.3333, 0, 0, 0.478587,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0260298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433897,-99) , 
4, 0.546169, 0, 0, 0.47853,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0261275);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414114,-99) , 
14, 34.8156, 1, 0, 0.479452,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0256826);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450476,-99) , 
2, -2.84239, 1, 0, 0.478595,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0259635);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374164,-99) , 
11, 1.41636, 1, 0, 0.48187,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.025298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451439,-99) , 
2, 2.84239, 0, 0, 0.479073,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0257339);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332615,-99) , 
3, 0.697849, 0, 0, 0.482321,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0242262);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45247,-99) , 
2, -2.84239, 1, 0, 0.478595,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0245777);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169924,-99) , 
14, 69.5477, 1, 0, 0.481683,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0245361);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454387,-99) , 
9, 116.666, 0, 0, 0.476802,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0235433);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391648,-99) , 
4, -0.134541, 0, 0, 0.480655,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0238229);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453038,-99) , 
2, 2.84239, 0, 0, 0.478459,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.023475);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.175973,-99) , 
14, 69.5477, 1, 0, 0.481513,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0236743);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445149,-99) , 
11, 0.629496, 1, 0, 0.476837,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0224856);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454914,-99) , 
2, -2.84239, 1, 0, 0.478723,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.022938);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343858,-99) , 
3, 0.697849, 0, 0, 0.481584,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0223945);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454845,-99) , 
2, 2.84239, 0, 0, 0.478255,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0223251);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182019,-99) , 
14, 69.5477, 1, 0, 0.481123,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0227098);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458388,-99) , 
9, 121.428, 0, 0, 0.476664,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0219732);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355804,-99) , 
11, 1.57374, 1, 0, 0.48062,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0213059);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455773,-99) , 
2, -2.84239, 1, 0, 0.477585,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0212025);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42632,-99) , 
14, 34.8156, 1, 0, 0.480292,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0210043);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309657,-99) , 
3, 0.546783, 0, 0, 0.47957,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0214025);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452038,-99) , 
1, 102.88, 0, 0, 0.476067,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0210011);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435958,-99) , 
12, 1.71429, 1, 0, 0.478352,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0204249);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45764,-99) , 
2, 2.84239, 0, 0, 0.478443,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0208225);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191397,-99) , 
14, 69.5477, 1, 0, 0.481053,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0208172);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455463,-99) , 
11, 0.472123, 1, 0, 0.476877,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0198198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437708,-99) , 
9, 83.3333, 0, 0, 0.479432,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0195946);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317095,-99) , 
3, 0.546783, 0, 0, 0.479386,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0201523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461215,-99) , 
9, 121.428, 0, 0, 0.476113,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0195571);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195284,-99) , 
14, 69.5477, 1, 0, 0.479625,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.019732);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456665,-99) , 
2, -2.84239, 1, 0, 0.475697,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.01929);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451456,-99) , 
4, 0.697438, 0, 0, 0.478198,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0190266);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394589,-99) , 
11, 1.41636, 1, 0, 0.479521,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0193259);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452281,-99) , 
2, 2.54319, 0, 0, 0.477461,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0184953);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.200521,-99) , 
14, 69.5477, 1, 0, 0.478976,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0191125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463285,-99) , 
9, 126.19, 0, 0, 0.475254,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0179137);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461253,-99) , 
2, -2.84239, 1, 0, 0.478872,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0185038);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328266,-99) , 
3, 0.546783, 0, 0, 0.481142,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0179829);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460188,-99) , 
11, 0.472123, 1, 0, 0.478046,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0182789);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.206442,-99) , 
14, 69.5477, 1, 0, 0.480253,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0182723);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459321,-99) , 
2, 2.84239, 0, 0, 0.476567,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.01737);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408922,-99) , 
4, -0.134541, 0, 0, 0.478894,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0173796);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461515,-99) , 
12, 0.857143, 1, 0, 0.477269,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0172198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211871,-99) , 
14, 69.5477, 1, 0, 0.479569,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0177858);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465331,-99) , 
9, 126.19, 0, 0, 0.47609,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0168879);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375871,-99) , 
11, 1.57374, 1, 0, 0.479457,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0169646);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461391,-99) , 
2, -2.84239, 1, 0, 0.477117,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0166239);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435742,-99) , 
14, 34.8156, 1, 0, 0.479264,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0166395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460826,-99) , 
1, 102.88, 0, 0, 0.478678,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0168318);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34725,-99) , 
0, 132.856, 1, 0, 0.480459,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0166831);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456598,-99) , 
2, 2.54319, 0, 0, 0.477743,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0161785);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336051,-99) , 
3, 0.546783, 0, 0, 0.479042,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0164811);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458694,-99) , 
6, 71.0251, 0, 0, 0.476333,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0159573);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457896,-99) , 
2, -2.54319, 1, 0, 0.477992,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0159667);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219741,-99) , 
14, 69.5477, 1, 0, 0.47923,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0163272);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46701,-99) , 
9, 126.19, 0, 0, 0.475995,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0157345);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447358,-99) , 
12, 1.71429, 1, 0, 0.479088,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0155581);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460713,-99) , 
4, 0.773072, 0, 0, 0.479156,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0158462);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225676,-99) , 
14, 69.5477, 1, 0, 0.480532,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0159009);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462615,-99) , 
11, 0.472123, 1, 0, 0.477316,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0152938);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352532,-99) , 
0, 132.856, 1, 0, 0.479269,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0157453);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462919,-99) , 
2, 2.84239, 0, 0, 0.476798,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0147709);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457,-99) , 
5, 69.4379, 0, 0, 0.478799,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0149566);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344802,-99) , 
3, 0.546783, 0, 0, 0.479564,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0151661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469277,-99) , 
1, 136.968, 0, 0, 0.477057,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0151214);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.229365,-99) , 
14, 69.5477, 1, 0, 0.479994,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0148932);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469237,-99) , 
9, 126.19, 0, 0, 0.476922,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0145174);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357947,-99) , 
0, 132.856, 1, 0, 0.479744,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0146614);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46472,-99) , 
2, -2.84239, 1, 0, 0.477395,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0145366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461088,-99) , 
2, 2.54319, 0, 0, 0.479245,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0145001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235507,-99) , 
14, 69.5477, 1, 0, 0.480372,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0145814);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462295,-99) , 
6, 71.0251, 0, 0, 0.47742,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0139502);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334751,-99) , 
3, 0.47125, 0, 0, 0.478889,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0144372);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469795,-99) , 
1, 136.968, 0, 0, 0.476451,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0138685);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462114,-99) , 
2, -2.54319, 1, 0, 0.479247,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0139821);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2395,-99) , 
14, 69.5477, 1, 0, 0.480318,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0140654);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466135,-99) , 
12, 0.857143, 1, 0, 0.477468,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0135865);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422096,-99) , 
4, -0.134541, 0, 0, 0.479328,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0137474);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461414,-99) , 
2, 2.54319, 0, 0, 0.478058,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0134921);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467182,-99) , 
11, 0.472123, 1, 0, 0.479121,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0138361);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364441,-99) , 
0, 132.856, 1, 0, 0.480778,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0132114);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472145,-99) , 
9, 126.19, 0, 0, 0.478537,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0137967);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372861,-99) , 
7, 93.5712, 1, 0, 0.48104,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0129838);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463221,-99) , 
2, -2.54319, 1, 0, 0.478877,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0131169);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244771,-99) , 
14, 69.5477, 1, 0, 0.479878,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0135399);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471267,-99) , 
1, 136.968, 0, 0, 0.477201,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0130931);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343204,-99) , 
3, 0.47125, 0, 0, 0.479822,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0131523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46694,-99) , 
2, 2.84239, 0, 0, 0.477532,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0125408);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467187,-99) , 
4, 0.848707, 0, 0, 0.479198,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0129587);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249008,-99) , 
14, 69.5477, 1, 0, 0.480542,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0126753);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472671,-99) , 
1, 136.968, 0, 0, 0.477895,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.012769);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369168,-99) , 
0, 132.856, 1, 0, 0.480349,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0125348);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460427,-99) , 
5, 69.4379, 0, 0, 0.478278,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0123465);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445348,-99) , 
14, 34.8156, 1, 0, 0.478928,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0124837);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466169,-99) , 
6, 71.0251, 0, 0, 0.478479,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0122724);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377496,-99) , 
7, 93.5712, 1, 0, 0.479738,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0124822);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46851,-99) , 
12, 0.857143, 1, 0, 0.477812,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0123218);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354608,-99) , 
7, 86.4286, 0, 0, 0.479462,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0124761);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472344,-99) , 
9, 126.19, 0, 0, 0.477354,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0121581);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336487,-99) , 
3, 0.395717, 0, 0, 0.479717,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.012261);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471045,-99) , 
11, 0.314749, 1, 0, 0.477518,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0119574);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413307,-99) , 
0, 104.285, 0, 0, 0.479533,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0119359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468916,-99) , 
2, -2.84239, 1, 0, 0.478103,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0120238);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371386,-99) , 
0, 132.856, 1, 0, 0.479604,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.012209);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46351,-99) , 
2, 2.54319, 0, 0, 0.477654,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.0115836);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465199,-99) , 
2, -2.54319, 1, 0, 0.478593,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0115725);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25606,-99) , 
14, 69.5477, 1, 0, 0.479483,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0120445);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472971,-99) , 
1, 136.968, 0, 0, 0.477112,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0114967);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400392,-99) , 
11, 1.57374, 1, 0, 0.479444,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0114935);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464781,-99) , 
2, 2.54319, 0, 0, 0.477848,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0112584);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46705,-99) , 
4, 0.773072, 0, 0, 0.478731,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0115869);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359812,-99) , 
7, 86.4286, 0, 0, 0.479733,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0114126);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473825,-99) , 
9, 126.19, 0, 0, 0.477748,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.0117431);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380823,-99) , 
7, 93.5712, 1, 0, 0.479909,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0111452);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474194,-99) , 
6, 96.2393, 0, 0, 0.478065,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.0114371);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343102,-99) , 
3, 0.395717, 0, 0, 0.480152,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0110185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475445,-99) , 
11, 0.157376, 1, 0, 0.478083,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.0115347);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.259954,-99) , 
14, 69.5477, 1, 0, 0.48036,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0109716);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470682,-99) , 
12, 0.857143, 1, 0, 0.477995,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0110628);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376314,-99) , 
0, 132.856, 1, 0, 0.479445,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.011046);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472706,-99) , 
5, 94.8626, 0, 0, 0.477649,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0111613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416489,-99) , 
0, 104.285, 0, 0, 0.479474,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.0108369);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466026,-99) , 
2, -2.54319, 1, 0, 0.478142,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0106972);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362978,-99) , 
7, 86.4286, 0, 0, 0.478972,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0109813);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.477138,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.010983);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384805,-99) , 
7, 93.5712, 1, 0, 0.479884,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.010655);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470769,-99) , 
2, 2.84239, 0, 0, 0.478158,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0106908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345432,-99) , 
0, 135.713, 1, 0, 0.479503,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.0108502);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474261,-99) , 
6, 96.2393, 0, 0, 0.477565,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.0106826);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331819,-99) , 
3, 0.320184, 0, 0, 0.479597,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.0107601);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.477598,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.0108999);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265008,-99) , 
14, 69.5477, 1, 0, 0.480288,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.0105525);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475958,-99) , 
11, 0.157376, 1, 0, 0.47805,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.0105282);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367731,-99) , 
7, 86.4286, 0, 0, 0.48023,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.0103633);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.478423,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.0108871);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327462,-99) , 
7, 94.9997, 1, 0, 0.481014,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.0102681);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433708,-99) , 
0, 107.143, 0, 0, 0.478945,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.0105586);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.478017,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.0107203);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349109,-99) , 
0, 135.713, 1, 0, 0.480657,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.0102329);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475768,-99) , 
9, 126.19, 0, 0, 0.478712,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.0105749);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336561,-99) , 
3, 0.320184, 0, 0, 0.480649,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0102447);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.47867,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.0108006);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.269934,-99) , 
14, 69.5477, 1, 0, 0.481231,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.0100923);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465242,-99) , 
5, 69.4379, 0, 0, 0.47901,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.0101617);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44889,-99) , 
6, 45.8109, 0, 0, 0.479534,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.0100576);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.479059,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.0105916);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273482,-99) , 
14, 69.5477, 1, 0, 0.481573,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.00997073);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425716,-99) , 
4, -0.210175, 0, 0, 0.479394,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.0104297);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.478285,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.0102995);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384522,-99) , 
0, 132.856, 1, 0, 0.480892,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.00998152);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.479217,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.0105937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332337,-99) , 
7, 94.9997, 1, 0, 0.481712,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.00987755);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370267,-99) , 
7, 86.4286, 0, 0, 0.479697,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.0105662);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.478001,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.00981223);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424099,-99) , 
0, 104.285, 0, 0, 0.480642,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.00985922);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.479472,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.0102767);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278031,-99) , 
14, 69.5477, 1, 0, 0.481936,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.00969202);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.479819,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0103935);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343893,-99) , 
3, 0.320184, 0, 0, 0.482242,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.00966164);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355378,-99) , 
0, 135.713, 1, 0, 0.480295,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0103067);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.478541,-99)    );
  // itree = 200
  fBoostWeights.push_back(0.00991831);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335387,-99) , 
7, 94.9997, 1, 0, 0.481117,-99)    );
  // itree = 201
  fBoostWeights.push_back(0.00997597);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.479229,-99)    );
  // itree = 202
  fBoostWeights.push_back(0.00999291);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375645,-99) , 
7, 86.4286, 0, 0, 0.481722,-99)    );
  // itree = 203
  fBoostWeights.push_back(0.00960258);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480005,-99)    );
  // itree = 204
  fBoostWeights.push_back(0.0101958);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385429,-99) , 
11, 1.73111, 1, 0, 0.482406,-99)    );
  // itree = 205
  fBoostWeights.push_back(0.00959198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461442,-99) , 
12, 1.71429, 1, 0, 0.480716,-99)    );
  // itree = 206
  fBoostWeights.push_back(0.00939849);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338188,-99) , 
7, 94.9997, 1, 0, 0.480757,-99)    );
  // itree = 207
  fBoostWeights.push_back(0.0101018);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.478967,-99)    );
  // itree = 208
  fBoostWeights.push_back(0.00960896);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282201,-99) , 
14, 69.5477, 1, 0, 0.481492,-99)    );
  // itree = 209
  fBoostWeights.push_back(0.00984054);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.47951,-99)    );
  // itree = 210
  fBoostWeights.push_back(0.00978259);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347697,-99) , 
3, 0.320184, 0, 0, 0.48197,-99)    );
  // itree = 211
  fBoostWeights.push_back(0.00953933);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480137,-99)    );
  // itree = 212
  fBoostWeights.push_back(0.00987515);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36482,-99) , 
13, 3.39895, 1, 0, 0.482521,-99)    );
  // itree = 213
  fBoostWeights.push_back(0.00924769);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480744,-99)    );
  // itree = 214
  fBoostWeights.push_back(0.00997891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362508,-99) , 
0, 135.713, 1, 0, 0.483055,-99)    );
  // itree = 215
  fBoostWeights.push_back(0.00951225);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439832,-99) , 
0, 107.143, 0, 0, 0.481241,-99)    );
  // itree = 216
  fBoostWeights.push_back(0.00942037);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480384,-99)    );
  // itree = 217
  fBoostWeights.push_back(0.00981301);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379906,-99) , 
7, 86.4286, 0, 0, 0.482739,-99)    );
  // itree = 218
  fBoostWeights.push_back(0.00916856);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397449,-99) , 
7, 93.5712, 1, 0, 0.481052,-99)    );
  // itree = 219
  fBoostWeights.push_back(0.00979408);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.479607,-99)    );
  // itree = 220
  fBoostWeights.push_back(0.00945467);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286342,-99) , 
14, 69.5477, 1, 0, 0.482055,-99)    );
  // itree = 221
  fBoostWeights.push_back(0.00955532);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480104,-99)    );
  // itree = 222
  fBoostWeights.push_back(0.0096126);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389224,-99) , 
11, 1.73111, 1, 0, 0.482492,-99)    );
  // itree = 223
  fBoostWeights.push_back(0.00917295);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480899,-99)    );
  // itree = 224
  fBoostWeights.push_back(0.00969133);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352935,-99) , 
3, 0.320184, 0, 0, 0.483192,-99)    );
  // itree = 225
  fBoostWeights.push_back(0.00902444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456901,-99) , 
9, 78.5714, 0, 0, 0.481375,-99)    );
  // itree = 226
  fBoostWeights.push_back(0.00908847);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481075,-99)    );
  // itree = 227
  fBoostWeights.push_back(0.00967673);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290357,-99) , 
14, 69.5477, 1, 0, 0.483346,-99)    );
  // itree = 228
  fBoostWeights.push_back(0.00897395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414297,-99) , 
0, 129.999, 1, 0, 0.481348,-99)    );
  // itree = 229
  fBoostWeights.push_back(0.00956706);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480079,-99)    );
  // itree = 230
  fBoostWeights.push_back(0.00929728);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368763,-99) , 
13, 3.39895, 1, 0, 0.48247,-99)    );
  // itree = 231
  fBoostWeights.push_back(0.00922256);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480796,-99)    );
  // itree = 232
  fBoostWeights.push_back(0.00943522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34685,-99) , 
7, 94.9997, 1, 0, 0.483101,-99)    );
  // itree = 233
  fBoostWeights.push_back(0.00897947);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481302,-99)    );
  // itree = 234
  fBoostWeights.push_back(0.00964022);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383469,-99) , 
7, 86.4286, 0, 0, 0.483546,-99)    );
  // itree = 235
  fBoostWeights.push_back(0.00911508);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429302,-99) , 
0, 104.285, 0, 0, 0.481888,-99)    );
  // itree = 236
  fBoostWeights.push_back(0.00921964);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480802,-99)    );
  // itree = 237
  fBoostWeights.push_back(0.00924531);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367998,-99) , 
0, 135.713, 1, 0, 0.483106,-99)    );
  // itree = 238
  fBoostWeights.push_back(0.00892042);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481424,-99)    );
  // itree = 239
  fBoostWeights.push_back(0.00938409);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357115,-99) , 
3, 0.320184, 0, 0, 0.483654,-99)    );
  // itree = 240
  fBoostWeights.push_back(0.00884295);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47203,-99) , 
2, -2.54319, 1, 0, 0.481894,-99)    );
  // itree = 241
  fBoostWeights.push_back(0.00909999);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47214,-99) , 
2, 2.54319, 0, 0, 0.482568,-99)    );
  // itree = 242
  fBoostWeights.push_back(0.00915653);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294972,-99) , 
14, 69.5477, 1, 0, 0.483262,-99)    );
  // itree = 243
  fBoostWeights.push_back(0.00894695);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481369,-99)    );
  // itree = 244
  fBoostWeights.push_back(0.00928966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372711,-99) , 
13, 3.39895, 1, 0, 0.483605,-99)    );
  // itree = 245
  fBoostWeights.push_back(0.00884592);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455264,-99) , 
6, 45.8109, 0, 0, 0.481932,-99)    );
  // itree = 246
  fBoostWeights.push_back(0.00887365);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481522,-99)    );
  // itree = 247
  fBoostWeights.push_back(0.00928417);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350572,-99) , 
7, 94.9997, 1, 0, 0.483739,-99)    );
  // itree = 248
  fBoostWeights.push_back(0.00866188);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470142,-99) , 
5, 69.4379, 0, 0, 0.481968,-99)    );
  // itree = 249
  fBoostWeights.push_back(0.0087522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385679,-99) , 
7, 86.4286, 0, 0, 0.482417,-99)    );
  // itree = 250
  fBoostWeights.push_back(0.00916705);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.480911,-99)    );
  // itree = 251
  fBoostWeights.push_back(0.00891663);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423419,-99) , 
4, -0.28581, 0, 0, 0.483202,-99)    );
  // itree = 252
  fBoostWeights.push_back(0.00864399);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481999,-99)    );
  // itree = 253
  fBoostWeights.push_back(0.00921562);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298712,-99) , 
14, 69.5477, 1, 0, 0.48416,-99)    );
  // itree = 254
  fBoostWeights.push_back(0.0085218);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482254,-99)    );
  // itree = 255
  fBoostWeights.push_back(0.00921213);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372686,-99) , 
0, 135.713, 1, 0, 0.484383,-99)    );
  // itree = 256
  fBoostWeights.push_back(0.00857459);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445209,-99) , 
0, 107.143, 0, 0, 0.482707,-99)    );
  // itree = 257
  fBoostWeights.push_back(0.00867438);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481936,-99)    );
  // itree = 258
  fBoostWeights.push_back(0.00902368);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354107,-99) , 
7, 94.9997, 1, 0, 0.484104,-99)    );
  // itree = 259
  fBoostWeights.push_back(0.00846032);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482382,-99)    );
  // itree = 260
  fBoostWeights.push_back(0.00907737);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398195,-99) , 
11, 1.73111, 1, 0, 0.484496,-99)    );
  // itree = 261
  fBoostWeights.push_back(0.00850989);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376148,-99) , 
13, 3.39895, 1, 0, 0.482991,-99)    );
  // itree = 262
  fBoostWeights.push_back(0.00890459);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481457,-99)    );
  // itree = 263
  fBoostWeights.push_back(0.00873327);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389735,-99) , 
7, 86.4286, 0, 0, 0.483682,-99)    );
  // itree = 264
  fBoostWeights.push_back(0.0085574);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48218,-99)    );
  // itree = 265
  fBoostWeights.push_back(0.00891705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302467,-99) , 
14, 69.5477, 1, 0, 0.484318,-99)    );
  // itree = 266
  fBoostWeights.push_back(0.00841661);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482473,-99)    );
  // itree = 267
  fBoostWeights.push_back(0.00901427);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363578,-99) , 
3, 0.320184, 0, 0, 0.484576,-99)    );
  // itree = 268
  fBoostWeights.push_back(0.00826684);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374343,-99) , 
0, 135.713, 1, 0, 0.482884,-99)    );
  // itree = 269
  fBoostWeights.push_back(0.00894182);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48138,-99)    );
  // itree = 270
  fBoostWeights.push_back(0.00848684);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356621,-99) , 
7, 94.9997, 1, 0, 0.483614,-99)    );
  // itree = 271
  fBoostWeights.push_back(0.00864669);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481994,-99)    );
  // itree = 272
  fBoostWeights.push_back(0.0085766);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418351,-99) , 
0, 101.428, 0, 0, 0.484155,-99)    );
  // itree = 273
  fBoostWeights.push_back(0.00821449);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482893,-99)    );
  // itree = 274
  fBoostWeights.push_back(0.0088305);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306518,-99) , 
14, 69.5477, 1, 0, 0.484946,-99)    );
  // itree = 275
  fBoostWeights.push_back(0.00813741);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379299,-99) , 
13, 3.39895, 1, 0, 0.483117,-99)    );
  // itree = 276
  fBoostWeights.push_back(0.0088116);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.481651,-99)    );
  // itree = 277
  fBoostWeights.push_back(0.00828447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366592,-99) , 
3, 0.320184, 0, 0, 0.483853,-99)    );
  // itree = 278
  fBoostWeights.push_back(0.0085008);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482297,-99)    );
  // itree = 279
  fBoostWeights.push_back(0.00848312);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393607,-99) , 
7, 86.4286, 0, 0, 0.484422,-99)    );
  // itree = 280
  fBoostWeights.push_back(0.00818181);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482961,-99)    );
  // itree = 281
  fBoostWeights.push_back(0.00865096);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360764,-99) , 
7, 94.9997, 1, 0, 0.485006,-99)    );
  // itree = 282
  fBoostWeights.push_back(0.00812199);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424678,-99) , 
11, 1.57374, 1, 0, 0.483353,-99)    );
  // itree = 283
  fBoostWeights.push_back(0.00853548);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482225,-99)    );
  // itree = 284
  fBoostWeights.push_back(0.00835265);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378874,-99) , 
0, 135.713, 1, 0, 0.484358,-99)    );
  // itree = 285
  fBoostWeights.push_back(0.00824145);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.482837,-99)    );
  // itree = 286
  fBoostWeights.push_back(0.00848304);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309864,-99) , 
14, 69.5477, 1, 0, 0.484897,-99)    );
  // itree = 287
  fBoostWeights.push_back(0.00809644);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483139,-99)    );
  // itree = 288
  fBoostWeights.push_back(0.00839306);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384481,-99) , 
13, 3.39895, 1, 0, 0.485162,-99)    );
  // itree = 289
  fBoostWeights.push_back(0.00797781);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474738,-99) , 
2, -2.54319, 1, 0, 0.483649,-99)    );
  // itree = 290
  fBoostWeights.push_back(0.00818076);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474879,-99) , 
2, 2.54319, 0, 0, 0.484255,-99)    );
  // itree = 291
  fBoostWeights.push_back(0.00830401);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421472,-99) , 
0, 101.428, 0, 0, 0.484877,-99)    );
  // itree = 292
  fBoostWeights.push_back(0.00785235);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459945,-99) , 
6, 45.8109, 0, 0, 0.483656,-99)    );
  // itree = 293
  fBoostWeights.push_back(0.00802194);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483294,-99)    );
  // itree = 294
  fBoostWeights.push_back(0.00843185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362821,-99) , 
7, 85.0001, 0, 0, 0.485299,-99)    );
  // itree = 295
  fBoostWeights.push_back(0.00785209);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438392,-99) , 
0, 127.142, 1, 0, 0.483684,-99)    );
  // itree = 296
  fBoostWeights.push_back(0.00827854);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48276,-99)    );
  // itree = 297
  fBoostWeights.push_back(0.00820361);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363747,-99) , 
7, 94.9997, 1, 0, 0.484829,-99)    );
  // itree = 298
  fBoostWeights.push_back(0.00803777);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483261,-99)    );
  // itree = 299
  fBoostWeights.push_back(0.00837728);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371353,-99) , 
3, 0.320184, 0, 0, 0.485269,-99)    );
  // itree = 300
  fBoostWeights.push_back(0.0078284);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483697,-99)    );
  // itree = 301
  fBoostWeights.push_back(0.00840412);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314415,-99) , 
14, 69.5477, 1, 0, 0.485653,-99)    );
  // itree = 302
  fBoostWeights.push_back(0.00772579);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48391,-99)    );
  // itree = 303
  fBoostWeights.push_back(0.00824272);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366537,-99) , 
7, 85.0001, 0, 0, 0.485841,-99)    );
  // itree = 304
  fBoostWeights.push_back(0.00776267);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43085,-99) , 
4, -0.28581, 0, 0, 0.484262,-99)    );
  // itree = 305
  fBoostWeights.push_back(0.00806009);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483214,-99)    );
  // itree = 306
  fBoostWeights.push_back(0.00801047);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387464,-99) , 
13, 3.39895, 1, 0, 0.485229,-99)    );
  // itree = 307
  fBoostWeights.push_back(0.0077866);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483784,-99)    );
  // itree = 308
  fBoostWeights.push_back(0.00819938);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367407,-99) , 
7, 94.9997, 1, 0, 0.485729,-99)    );
  // itree = 309
  fBoostWeights.push_back(0.00770244);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457011,-99) , 
9, 73.8095, 0, 0, 0.484162,-99)    );
  // itree = 310
  fBoostWeights.push_back(0.00784471);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483663,-99)    );
  // itree = 311
  fBoostWeights.push_back(0.00807182);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317697,-99) , 
14, 69.5477, 1, 0, 0.485623,-99)    );
  // itree = 312
  fBoostWeights.push_back(0.00770755);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483948,-99)    );
  // itree = 313
  fBoostWeights.push_back(0.00812977);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385885,-99) , 
0, 135.713, 1, 0, 0.485874,-99)    );
  // itree = 314
  fBoostWeights.push_back(0.0077877);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450427,-99) , 
0, 107.143, 0, 0, 0.484393,-99)    );
  // itree = 315
  fBoostWeights.push_back(0.00782964);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483694,-99)    );
  // itree = 316
  fBoostWeights.push_back(0.00804831);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407821,-99) , 
11, 1.73111, 1, 0, 0.485651,-99)    );
  // itree = 317
  fBoostWeights.push_back(0.00757621);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46908,-99) , 
12, 1.71429, 1, 0, 0.484316,-99)    );
  // itree = 318
  fBoostWeights.push_back(0.00751585);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484347,-99)    );
  // itree = 319
  fBoostWeights.push_back(0.00813298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331517,-99) , 
7, 83.5716, 0, 0, 0.486225,-99)    );
  // itree = 320
  fBoostWeights.push_back(0.00749607);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375691,-99) , 
3, 0.320184, 0, 0, 0.484561,-99)    );
  // itree = 321
  fBoostWeights.push_back(0.00808971);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483153,-99)    );
  // itree = 322
  fBoostWeights.push_back(0.00766217);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416424,-99) , 
7, 93.5712, 1, 0, 0.485174,-99)    );
  // itree = 323
  fBoostWeights.push_back(0.00770072);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483962,-99)    );
  // itree = 324
  fBoostWeights.push_back(0.00784358);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321486,-99) , 
14, 69.5477, 1, 0, 0.485887,-99)    );
  // itree = 325
  fBoostWeights.push_back(0.00755854);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484258,-99)    );
  // itree = 326
  fBoostWeights.push_back(0.00789791);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391492,-99) , 
13, 3.39895, 1, 0, 0.486147,-99)    );
  // itree = 327
  fBoostWeights.push_back(0.00739508);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443588,-99) , 
5, 44.0131, 0, 0, 0.484722,-99)    );
  // itree = 328
  fBoostWeights.push_back(0.00774168);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483877,-99)    );
  // itree = 329
  fBoostWeights.push_back(0.00776573);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388377,-99) , 
0, 135.713, 1, 0, 0.485812,-99)    );
  // itree = 330
  fBoostWeights.push_back(0.00749219);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484396,-99)    );
  // itree = 331
  fBoostWeights.push_back(0.00790367);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33414,-99) , 
7, 83.5716, 0, 0, 0.486269,-99)    );
  // itree = 332
  fBoostWeights.push_back(0.00741538);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425459,-99) , 
0, 101.428, 0, 0, 0.48465,-99)    );
  // itree = 333
  fBoostWeights.push_back(0.00789373);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483561,-99)    );
  // itree = 334
  fBoostWeights.push_back(0.00745176);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380038,-99) , 
11, 1.88848, 1, 0, 0.485533,-99)    );
  // itree = 335
  fBoostWeights.push_back(0.00761824);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484134,-99)    );
  // itree = 336
  fBoostWeights.push_back(0.00765112);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373245,-99) , 
7, 94.9997, 1, 0, 0.486038,-99)    );
  // itree = 337
  fBoostWeights.push_back(0.00740672);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484574,-99)    );
  // itree = 338
  fBoostWeights.push_back(0.00777712);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324993,-99) , 
14, 69.5477, 1, 0, 0.486425,-99)    );
  // itree = 339
  fBoostWeights.push_back(0.00729358);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48481,-99)    );
  // itree = 340
  fBoostWeights.push_back(0.00782595);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381046,-99) , 
3, 0.320184, 0, 0, 0.486632,-99)    );
  // itree = 341
  fBoostWeights.push_back(0.00723117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430754,-99) , 
7, 87.8572, 0, 0, 0.485162,-99)    );
  // itree = 342
  fBoostWeights.push_back(0.00761865);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484133,-99)    );
  // itree = 343
  fBoostWeights.push_back(0.00744253);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391563,-99) , 
0, 135.713, 1, 0, 0.486037,-99)    );
  // itree = 344
  fBoostWeights.push_back(0.00735586);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48468,-99)    );
  // itree = 345
  fBoostWeights.push_back(0.00757308);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395127,-99) , 
13, 3.39895, 1, 0, 0.486518,-99)    );
  // itree = 346
  fBoostWeights.push_back(0.00716617);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475321,-99) , 
2, -2.24399, 1, 0, 0.485151,-99)    );
  // itree = 347
  fBoostWeights.push_back(0.00731019);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477221,-99) , 
2, 2.54319, 0, 0, 0.48552,-99)    );
  // itree = 348
  fBoostWeights.push_back(0.00739617);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428983,-99) , 
0, 101.428, 0, 0, 0.486075,-99)    );
  // itree = 349
  fBoostWeights.push_back(0.00720814);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484988,-99)    );
  // itree = 350
  fBoostWeights.push_back(0.00761435);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376552,-99) , 
7, 94.9997, 1, 0, 0.486789,-99)    );
  // itree = 351
  fBoostWeights.push_back(0.00705805);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338274,-99) , 
7, 83.5716, 0, 0, 0.485332,-99)    );
  // itree = 352
  fBoostWeights.push_back(0.00773736);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.483886,-99)    );
  // itree = 353
  fBoostWeights.push_back(0.00718868);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383343,-99) , 
11, 1.88848, 1, 0, 0.485819,-99)    );
  // itree = 354
  fBoostWeights.push_back(0.00745695);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48447,-99)    );
  // itree = 355
  fBoostWeights.push_back(0.00737011);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328784,-99) , 
14, 69.5477, 1, 0, 0.486333,-99)    );
  // itree = 356
  fBoostWeights.push_back(0.00729774);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484801,-99)    );
  // itree = 357
  fBoostWeights.push_back(0.00742286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384321,-99) , 
3, 0.320184, 0, 0, 0.486625,-99)    );
  // itree = 358
  fBoostWeights.push_back(0.00709173);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48523,-99)    );
  // itree = 359
  fBoostWeights.push_back(0.00743785);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342674,-99) , 
7, 83.5716, 0, 0, 0.487002,-99)    );
  // itree = 360
  fBoostWeights.push_back(0.00697267);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485478,-99)    );
  // itree = 361
  fBoostWeights.push_back(0.00747674);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379489,-99) , 
7, 94.9997, 1, 0, 0.48722,-99)    );
  // itree = 362
  fBoostWeights.push_back(0.00698199);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396925,-99) , 
13, 3.39895, 1, 0, 0.485789,-99)    );
  // itree = 363
  fBoostWeights.push_back(0.00742844);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.484529,-99)    );
  // itree = 364
  fBoostWeights.push_back(0.00716748);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394856,-99) , 
0, 135.713, 1, 0, 0.486385,-99)    );
  // itree = 365
  fBoostWeights.push_back(0.00716458);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485078,-99)    );
  // itree = 366
  fBoostWeights.push_back(0.00729493);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332414,-99) , 
14, 69.5477, 1, 0, 0.486869,-99)    );
  // itree = 367
  fBoostWeights.push_back(0.0070333);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485351,-99)    );
  // itree = 368
  fBoostWeights.push_back(0.00727263);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432101,-99) , 
0, 101.428, 0, 0, 0.487109,-99)    );
  // itree = 369
  fBoostWeights.push_back(0.00693896);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465244,-99) , 
6, 45.8109, 0, 0, 0.48604,-99)    );
  // itree = 370
  fBoostWeights.push_back(0.00685513);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485722,-99)    );
  // itree = 371
  fBoostWeights.push_back(0.00736021);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345706,-99) , 
7, 83.5716, 0, 0, 0.487435,-99)    );
  // itree = 372
  fBoostWeights.push_back(0.00683378);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438582,-99) , 
4, -0.28581, 0, 0, 0.485927,-99)    );
  // itree = 373
  fBoostWeights.push_back(0.0072002);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485004,-99)    );
  // itree = 374
  fBoostWeights.push_back(0.00702726);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335075,-99) , 
14, 69.5477, 1, 0, 0.486803,-99)    );
  // itree = 375
  fBoostWeights.push_back(0.00703812);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485341,-99)    );
  // itree = 376
  fBoostWeights.push_back(0.00715091);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388654,-99) , 
11, 1.88848, 1, 0, 0.4871,-99)    );
  // itree = 377
  fBoostWeights.push_back(0.00683838);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485757,-99)    );
  // itree = 378
  fBoostWeights.push_back(0.00724747);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382445,-99) , 
7, 94.9997, 1, 0, 0.487466,-99)    );
  // itree = 379
  fBoostWeights.push_back(0.00672746);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462292,-99) , 
9, 73.8095, 0, 0, 0.486079,-99)    );
  // itree = 380
  fBoostWeights.push_back(0.006894);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485641,-99)    );
  // itree = 381
  fBoostWeights.push_back(0.00717705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398321,-99) , 
0, 135.713, 1, 0, 0.487364,-99)    );
  // itree = 382
  fBoostWeights.push_back(0.00669521);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.486055,-99)    );
  // itree = 383
  fBoostWeights.push_back(0.00727949);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389783,-99) , 
3, 0.320184, 0, 0, 0.487728,-99)    );
  // itree = 384
  fBoostWeights.push_back(0.00674107);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400657,-99) , 
13, 3.39895, 1, 0, 0.48636,-99)    );
  // itree = 385
  fBoostWeights.push_back(0.00713347);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485143,-99)    );
  // itree = 386
  fBoostWeights.push_back(0.00693374);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347716,-99) , 
7, 83.5716, 0, 0, 0.486925,-99)    );
  // itree = 387
  fBoostWeights.push_back(0.0069601);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485504,-99)    );
  // itree = 388
  fBoostWeights.push_back(0.00695325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338224,-99) , 
14, 69.5477, 1, 0, 0.487243,-99)    );
  // itree = 389
  fBoostWeights.push_back(0.00681973);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485796,-99)    );
  // itree = 390
  fBoostWeights.push_back(0.00694095);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385197,-99) , 
7, 94.9997, 1, 0, 0.4875,-99)    );
  // itree = 391
  fBoostWeights.push_back(0.00664137);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449088,-99) , 
5, 44.0131, 0, 0, 0.486171,-99)    );
  // itree = 392
  fBoostWeights.push_back(0.0070044);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485412,-99)    );
  // itree = 393
  fBoostWeights.push_back(0.00678111);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350517,-99) , 
7, 83.5716, 0, 0, 0.487162,-99)    );
  // itree = 394
  fBoostWeights.push_back(0.00683172);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.485771,-99)    );
  // itree = 395
  fBoostWeights.push_back(0.00683915);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376891,-99) , 
3, 0.244651, 0, 0, 0.487478,-99)    );
  // itree = 396
  fBoostWeights.push_back(0.00665504);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.486139,-99)    );
  // itree = 397
  fBoostWeights.push_back(0.00692633);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401739,-99) , 
0, 135.713, 1, 0, 0.487802,-99)    );
  // itree = 398
  fBoostWeights.push_back(0.0066842);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457388,-99) , 
0, 107.143, 0, 0, 0.486538,-99)    );
  // itree = 399
  fBoostWeights.push_back(0.00675064);
  fForest.push_back( 
NN(
0, 
0, 
0, 95.7143, 0, -1, 0.48594,-99)    );
   return;
};
 
// Clean up
inline void Readgg_plus_depth1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Readgg_plus_depth1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
